services:
  translet:
    build: .
    image: elcamilet/translet:latest
    ports:
      - "${PORT}:3000"
    environment:
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - PORT=${PORT}
    restart: unless-stopped
